### ISSUE TITLE
Tagging problem of the structures.

### ISSUE THREAD

**Issue by Cornebre** [A-xis/Jay_Infrastructure_Pack#6]
Some of the structure added by the mod are not tagged with their type / faction
![image](https://github.com/A-xis/Jay_Infrastructure_Pack/assets/110044432/02f663a4-56af-4b8f-87d6-702980f3c3cd)
![image](https://github.com/A-xis/Jay_Infrastructure_Pack/assets/110044432/f48cd8d0-a876-435f-b927-36b58e6e1369)

**Comment by A-xis** [comment]
Can't reproduce.
![image](https://github.com/A-xis/Jay_Infrastructure_Pack/assets/2327024/23609bea-32f8-438a-a66d-7465cd166a78)
